### ISSUE TITLE
whsasf 新作品，稍后提交PR

### ISSUE THREAD

**Issue by whsasf** [LCTT/logo#43]
你好版主，

之前创建的 PR还没有批准， 我还有一个新的PR需要提交，但是不想撤回之前的（因为关系到时间）。我等你把目前提交的批准了，我再提交pull request. 我把作品先放到这个 issue 里面了，作为凭证。

![logo9](https://user-images.githubusercontent.com/21168867/67147164-ecb04e80-f2c4-11e9-9622-d3edf981f156.png)

**Comment by ice-kylin** [comment]
你知道吗，你并不需要一个新的PR，你新的作品会和原来的一起合并到master（￣▽￣）
