### ISSUE TITLE
logo投稿

### ISSUE THREAD

**Issue by ghost** [LCTT/logo#49]
![logo](https://user-images.githubusercontent.com/56799406/67163975-1f7f4300-f3a8-11e9-943d-6a31a96c14c5.png)
完全搞不懂，折腾一晚上连截止日期都过了。

**Comment by ghost** [comment]
就只能投在这里了

**Comment by wxy** [comment]
没事没事

**Comment by ghost** [comment]
实在是太感谢了， keep in touch

[Jerry - Chat @ Spike](https://www.spikenow.com/?ref=spike-organic-signature&_ts=7pdaq)	[7pdaq]

On October 21, 2019 at 8:20 GMT, Xingyu Wang <notifications@github.com> wrote:

没事没事
