### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by wangshijun-shexian** [LCTT/logo#5]
1、尽量保留原logo元素，以维持用户记忆，修正添加主旨元素；
2、保留的元素有①灰黑色背景色调②大写字母L③网址④整体造型；
3、改变的元素有①底部绿色改成更新的苹果绿，与时俱进②绿色范围减小，去掉网址，可与圆形内接等边三角形贴合，增加图形稳定性，给放大主logo元素让出空间③大写字母L放大，去掉隔断，填充网址④L东侧是大写字母C，颜色与底部颜色相同，可以凸显原logo架构，主体形状与L相似，东北部加等腰直角三角形，与L共同组成正方形，该正方形可联想成向东怒吼的雄狮侧面部，寓意Linux中国在中国大地孔武有力，大有作为；
4、新logo可方可圆，黑白阴阳稿也一样简洁醒目，可用于各类应用场合。

**Comment by wxy** [comment]
不是发起 issue 提交，而是发起 Pull Request 来提交。
